version: '3.8'

services:
  gptlite:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
      - AZURE_OPENAI_API_BASE_URL=
      - AZURE_OPENAI_API_KEY=
      - AZURE_OPENAI_DEPLOYMENT=
      - AZURE_OPENAI_API_VERSION=
